services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: gitgalaxy-postgres-dev
    environment:
      POSTGRES_DB: gitgalaxy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data

<<<<<<< feat/2-scheduler
=======
  backend:
    build: .
    container_name: gitgalaxy-backend-dev
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_HOST: postgres
    ports:
      - "8080:8080"

>>>>>>> main
volumes:
  postgres-dev-data: